-- CreateTable
CREATE TABLE `tb_approved` (
    `id` INTEGER NOT NULL,
    `bulan` DATE NOT NULL,
    `status` INTEGER NOT NULL,
    `form` VARCHAR(10) NOT NULL,
    `create_by` VARCHAR(30) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_cmd_limit` (
    `limit_id` INTEGER NOT NULL,
    `site_id` VARCHAR(2) NOT NULL,
    `limit_cso` VARCHAR(200) NOT NULL,
    `limit_start` DATE NOT NULL,
    `limit_end` DATE NOT NULL,
    `limit_expire` DATE NOT NULL,
    `limit_add` VARCHAR(10) NOT NULL,
    `limit_edit` VARCHAR(10) NOT NULL,
    `limit_delete` VARCHAR(10) NOT NULL,
    `create_by` VARCHAR(30) NOT NULL,
    `modify_by` VARCHAR(30) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL,
    `trash` INTEGER NOT NULL,

    PRIMARY KEY (`limit_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_daerah` (
    `daerah_id` INTEGER NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `site_id` VARCHAR(100) NOT NULL,
    `daerah_kode` VARCHAR(100) NOT NULL,
    `daerah_kode_lama` VARCHAR(30) NOT NULL,
    `daerah_titel` VARCHAR(200) NOT NULL,
    `daerah_titel_eng` VARCHAR(200) NOT NULL,
    `daerah_alias` VARCHAR(200) NOT NULL,
    `daerah_paren` VARCHAR(100) NOT NULL,
    `daerah_tipe` VARCHAR(100) NOT NULL,
    `daerah_latitude` VARCHAR(10) NOT NULL,
    `daerah_longitude` VARCHAR(10) NOT NULL,
    `daerah_path` TEXT NOT NULL,
    `active` INTEGER NOT NULL,
    `create_by` VARCHAR(100) NOT NULL,
    `modify_by` VARCHAR(100) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL,
    `trash` INTEGER NOT NULL,

    INDEX `active`(`active`),
    INDEX `daerah_kode`(`daerah_kode`),
    INDEX `daerah_paren`(`daerah_paren`),
    INDEX `daerah_tipe`(`daerah_tipe`),
    INDEX `uuid`(`uuid`),
    PRIMARY KEY (`daerah_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_daerah_siha` (
    `id` INTEGER NOT NULL,
    `site_id` INTEGER NOT NULL,
    `daerah_kode` VARCHAR(100) NOT NULL,
    `daerah_titel` VARCHAR(100) NOT NULL,
    `daerah_alias` VARCHAR(100) NOT NULL,
    `daerah_paren` VARCHAR(20) NOT NULL,
    `daerah_tipe` VARCHAR(30) NOT NULL,
    `loc_x` VARCHAR(30) NOT NULL,
    `loc_y` VARCHAR(30) NOT NULL,
    `flag` ENUM('1', '0') NOT NULL,
    `create_by` VARCHAR(30) NOT NULL,
    `modify_by` VARCHAR(30) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL,

    INDEX `daerah_kode`(`daerah_kode`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_epi_pkm` (
    `pkm_id` INTEGER NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `GlobalRecordId` VARCHAR(100) NOT NULL,
    `site_id` VARCHAR(2) NOT NULL,
    `pkm_titel` VARCHAR(200) NOT NULL,
    `pkm_titel2` VARCHAR(200) NOT NULL,
    `pkm_alias` VARCHAR(200) NOT NULL,
    `pkm_kode` VARCHAR(15) NOT NULL,
    `pkm_kode2` VARCHAR(30) NOT NULL,
    `pkm_cp` VARCHAR(200) NOT NULL,
    `pkm_wilayah` VARCHAR(15) NOT NULL,
    `pkm_wilayah2` VARCHAR(15) NOT NULL,
    `pkm_wilayah_backup` VARCHAR(15) NOT NULL,
    `pkm_wilayah_lama` VARCHAR(15) NOT NULL,
    `pkm_alamat` VARCHAR(200) NOT NULL,
    `pkm_telepon` VARCHAR(15) NOT NULL,
    `pkm_fax` VARCHAR(15) NOT NULL,
    `pkm_email` VARCHAR(200) NOT NULL,
    `pkm_buka` VARCHAR(100) NOT NULL,
    `pkm_tutup` VARCHAR(100) NOT NULL,
    `pkm_supported` VARCHAR(50) NOT NULL,
    `pkm_ket` VARCHAR(200) NOT NULL,
    `create_by` VARCHAR(30) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_by` VARCHAR(30) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL,
    `trash` INTEGER NOT NULL,

    INDEX `pkm_kode`(`pkm_kode`),
    INDEX `pkm_supported`(`pkm_supported`),
    INDEX `pkm_titel`(`pkm_titel`),
    INDEX `trash`(`trash`),
    INDEX `uuid`(`uuid`),
    PRIMARY KEY (`pkm_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_epi_target` (
    `tar_id` INTEGER NOT NULL,
    `instansi_kode` VARCHAR(10) NOT NULL,
    `tar_berlaku` DATE NOT NULL,
    `tar_kadaluarsa` DATE NOT NULL,
    `tar_reached` VARCHAR(10) NOT NULL,
    `tar_tested` VARCHAR(10) NOT NULL,
    `tar_hiv` VARCHAR(10) NOT NULL,
    `tar_enrolled` VARCHAR(10) NOT NULL,
    `tar_know_enrolled` VARCHAR(10) NOT NULL,
    `tar_carecomm` VARCHAR(10) NOT NULL,
    `tar_pra_art` VARCHAR(10) NOT NULL,
    `tar_init_art` VARCHAR(10) NOT NULL,
    `tar_art` VARCHAR(10) NOT NULL,
    `tar_retain` VARCHAR(10) NOT NULL,
    `tar_re_enrolled` VARCHAR(10) NOT NULL,
    `tar_reenggaged` VARCHAR(10) NOT NULL,
    `tar_out_incare` VARCHAR(10) NOT NULL,
    `tar_partner_reached` VARCHAR(10) NOT NULL,
    `tar_partner_tested` VARCHAR(10) NOT NULL,
    `tar_partner_hiv` VARCHAR(10) NOT NULL,
    `tar_partner_enrolled` VARCHAR(10) NOT NULL,
    `tar_partner_know_enrolled` VARCHAR(10) NOT NULL,
    `tar_partner_carecomm` VARCHAR(10) NOT NULL,
    `tar_partner_pra_art` VARCHAR(10) NOT NULL,
    `tar_partner_init_art` VARCHAR(10) NOT NULL,
    `tar_partner_art` VARCHAR(10) NOT NULL,
    `tar_partner_retain` VARCHAR(10) NOT NULL,
    `tar_partner_re_enrolled` VARCHAR(10) NOT NULL,
    `tar_partner_reenggaged` VARCHAR(10) NOT NULL,
    `tar_partner_out_incare` VARCHAR(10) NOT NULL,
    `tar_ket` VARCHAR(100) NOT NULL,
    `create_by` VARCHAR(30) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_by` VARCHAR(30) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL,
    `site_id` VARCHAR(100) NOT NULL,

    INDEX `instansi_kode`(`instansi_kode`),
    PRIMARY KEY (`tar_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_epi_target_2020` (
    `no` INTEGER NOT NULL,
    `id` VARCHAR(50) NOT NULL,
    `mulai` DATE NOT NULL,
    `akhir` DATE NOT NULL,
    `reached` DECIMAL(10, 2) NOT NULL,
    `tested` DECIMAL(10, 2) NOT NULL,
    `plhiv` DECIMAL(10, 2) NOT NULL,
    `registered` DECIMAL(10, 2) NOT NULL,
    `case_managed` DECIMAL(10, 2) NOT NULL,
    `index_testing` DECIMAL(10, 2) NOT NULL,
    `tested_pn` DECIMAL(10, 2) NOT NULL,
    `plhiv_pn` DECIMAL(10, 2) NOT NULL,
    `registered_pn` DECIMAL(10, 2) NOT NULL,
    `retained` DECIMAL(10, 2) NOT NULL,
    `viral_load` DECIMAL(10, 2) NOT NULL,
    `re_engage` DECIMAL(10, 2) NOT NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `create_by` VARCHAR(30) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_by` VARCHAR(30) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL,

    INDEX `akhir`(`akhir`),
    INDEX `instansi_kode`(`id`),
    INDEX `kode_cso`(`kode_cso`),
    INDEX `mulai`(`mulai`),
    PRIMARY KEY (`no`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_epi_unit` (
    `unit_id` INTEGER NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `site_id` VARCHAR(2) NOT NULL,
    `unit_titel` VARCHAR(200) NOT NULL,
    `unit_alias` VARCHAR(200) NOT NULL,
    `unit_kode` VARCHAR(5) NOT NULL,
    `unit_odk` VARCHAR(50) NOT NULL,
    `unit_dokling` VARCHAR(15) NOT NULL,
    `unit_paren` VARCHAR(10) NOT NULL,
    `unit_tipe` VARCHAR(50) NOT NULL,
    `unit_alamat` VARCHAR(200) NOT NULL,
    `unit_area_prov` VARCHAR(200) NOT NULL,
    `unit_area_kab` VARCHAR(200) NOT NULL,
    `unit_area_kec` TEXT NOT NULL,
    `unit_wilayah` TEXT NOT NULL,
    `unit_email` VARCHAR(200) NOT NULL,
    `unit_hp` VARCHAR(15) NOT NULL,
    `unit_fax` VARCHAR(15) NOT NULL,
    `unit_klien` VARCHAR(200) NOT NULL,
    `unit_klien_partner` VARCHAR(255) NOT NULL,
    `unit_mitra` TEXT NOT NULL,
    `unit_limit_start` DATE NOT NULL,
    `unit_limit_end` DATE NOT NULL,
    `unit_limit_expired` DATE NOT NULL,
    `active` INTEGER NOT NULL,
    `create_by` VARCHAR(30) NOT NULL,
    `modify_by` VARCHAR(30) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL,
    `trash` INTEGER NOT NULL,

    INDEX `active`(`active`),
    INDEX `trash`(`trash`),
    INDEX `unit_kode`(`unit_kode`),
    PRIMARY KEY (`unit_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_filtering` (
    `id` INTEGER NOT NULL,
    `pid` VARCHAR(200) NOT NULL,
    `uri` VARCHAR(200) NOT NULL,
    `str_data` TEXT NOT NULL,
    `created_by` VARCHAR(50) NULL,
    `reported_at` DATETIME(0) NULL,
    `created_at` DATETIME(0) NULL,
    `updated_at` DATETIME(0) NULL,
    `deleted_at` DATETIME(0) NULL,

    INDEX `id`(`id`),
    PRIMARY KEY (`pid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form1a` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `metode_kontak` VARCHAR(50) NOT NULL,
    `jumlah_kontak` INTEGER NOT NULL,
    `kategori_kontak` VARCHAR(15) NOT NULL,
    `uic` VARCHAR(10) NULL,
    `nik` VARCHAR(16) NULL,
    `umur` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NOT NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NULL,
    `category2` VARCHAR(200) NOT NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `district` VARCHAR(10) NULL,
    `kecamatan` VARCHAR(12) NULL,
    `kelurahan` VARCHAR(15) NULL,
    `kelurahan2` VARCHAR(30) NOT NULL,
    `lokasi_kontak` VARCHAR(100) NULL,
    `phone` VARCHAR(20) NOT NULL,
    `phone_number` VARCHAR(15) NOT NULL,
    `ktp` VARCHAR(3) NULL,
    `ktp_ya` VARCHAR(100) NULL,
    `asuransi` VARCHAR(3) NULL,
    `asuransi_ya` VARCHAR(100) NULL,
    `mulai_prep` DATE NULL,
    `kunjungan_prep_terakhir` DATE NULL,
    `kunjungan_bukan_ke` VARCHAR(25) NULL,
    `kunjungan_bukan_ke_detail` INTEGER NOT NULL,
    `untuk_berapa_bulan_prep` INTEGER NULL,
    `dimana_pelayanan_prep` VARCHAR(50) NULL,
    `rejimen_prep` VARCHAR(25) NULL,
    `pernah_melewatkan_prep` VARCHAR(25) NULL,
    `masih_akses_prep` VARCHAR(50) NULL,
    `efek_samping` VARCHAR(50) NULL,
    `seks_selalu_pakai_kondom` VARCHAR(5) NULL,
    `tes_hiv_terakhir` DATE NULL,
    `jadwal_tes_hiv` DATE NULL,
    `kondom` INTEGER NOT NULL,
    `pelicin` INTEGER NOT NULL,
    `media_kie` INTEGER NOT NULL,
    `klien_adalah` VARCHAR(50) NOT NULL,
    `tes` VARCHAR(3) NULL,
    `tes_layanan` VARCHAR(10) NULL,
    `prep` VARCHAR(15) NULL,
    `tb` VARCHAR(3) NULL,
    `ims` VARCHAR(3) NULL,
    `gbv` VARCHAR(3) NULL,
    `tes_lainnya` VARCHAR(100) NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `nama_cbs_plus` VARCHAR(50) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NULL,
    `kode_parent_cbs` VARCHAR(100) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `tgl_review` DATE NOT NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `create_by` VARCHAR(50) NOT NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `created_at` DATETIME(0) NULL,
    `updated_at` DATETIME(0) NULL,
    `deleted_at` DATETIME(0) NULL,
    `trash` INTEGER NOT NULL,

    INDEX `category`(`category`),
    INDEX `cso`(`cso`),
    INDEX `distrik`(`district`),
    INDEX `gender`(`gender`),
    INDEX `kecamatan`(`kecamatan`),
    INDEX `kelurahan`(`kelurahan`),
    INDEX `kode_cso`(`kode_cso`),
    INDEX `kode_nama_cbs`(`kode_nama_cbs`),
    INDEX `kps_sp`(`kps_sp`),
    INDEX `no`(`no`),
    INDEX `prep`(`prep`),
    INDEX `reported`(`reported`),
    INDEX `tb`(`tb`),
    INDEX `tes_dokling`(`tes`),
    INDEX `tes_layanan`(`tes_layanan`),
    INDEX `tgl_kontak`(`tgl_kontak`),
    INDEX `tipe_cbs`(`tipe_cbs`),
    INDEX `tipe_kd`(`tipe_kd`),
    INDEX `trash`(`trash`),
    INDEX `uic`(`uic`),
    INDEX `uuid`(`uuid`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form2` (
    `no` INTEGER NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `metode_kontak` VARCHAR(50) NOT NULL,
    `uic` VARCHAR(10) NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `umur` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NULL,
    `category2` VARCHAR(200) NOT NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `district` VARCHAR(10) NULL,
    `kecamatan` VARCHAR(12) NULL,
    `kelurahan` VARCHAR(15) NULL,
    `manajemen_kasus` VARCHAR(100) NOT NULL,
    `lokasi_kontak` VARCHAR(100) NULL,
    `asal_klien` VARCHAR(15) NOT NULL,
    `phone` VARCHAR(20) NOT NULL,
    `phone_number` VARCHAR(15) NOT NULL,
    `ktp` VARCHAR(3) NULL,
    `ktp_ya` VARCHAR(100) NULL,
    `asuransi` VARCHAR(3) NULL,
    `asuransi_ya` VARCHAR(100) NULL,
    `dirujuk_oleh` VARCHAR(100) NOT NULL,
    `dirujuk_oleh_detil` VARCHAR(200) NOT NULL,
    `kunjungan` VARCHAR(100) NOT NULL,
    `no_regnas` VARCHAR(50) NOT NULL,
    `kapan_terdiagnosis_hiv` VARCHAR(50) NULL,
    `tanggal_terdiagnosis_hiv` DATE NULL,
    `pernah_terdaftar_perawatan` VARCHAR(50) NOT NULL,
    `terakhir_akses_layanan` VARCHAR(100) NOT NULL,
    `mekanisme` VARCHAR(50) NOT NULL,
    `mekanisme_detail` VARCHAR(100) NOT NULL,
    `hasil_telusur` VARCHAR(100) NOT NULL,
    `hasil_telusur_meninggal` VARCHAR(50) NOT NULL,
    `faktor_menghambat_perawatan` TEXT NOT NULL,
    `faktor_menghambat_perawatan_lainnya` VARCHAR(200) NOT NULL,
    `pendampingan_rujukan` VARCHAR(5) NOT NULL,
    `media_kie` VARCHAR(3) NOT NULL,
    `kartu_kontak_cbsplus` VARCHAR(3) NOT NULL,
    `transportasi` VARCHAR(5) NOT NULL,
    `butuh_bantuan_cbs_plus` VARCHAR(5) NOT NULL,
    `re_engage` VARCHAR(3) NOT NULL,
    `speak_health_worker` VARCHAR(3) NOT NULL,
    `rujukan_klien` VARCHAR(200) NOT NULL,
    `klien_adalah` VARCHAR(50) NOT NULL,
    `rencana_bertemu_lagi` VARCHAR(15) NOT NULL,
    `merujuk_cbs_plus` VARCHAR(5) NOT NULL,
    `rujukan_diberikan` VARCHAR(200) NOT NULL,
    `rujukan_diberikan_lain` VARCHAR(200) NOT NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `nama_cbs_plus` VARCHAR(50) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NULL,
    `kode_parent_cbs` VARCHAR(100) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `tgl_review` DATE NOT NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `create_date` DATETIME(0) NOT NULL,
    `create_by` VARCHAR(50) NOT NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NULL,
    `trash` INTEGER NOT NULL,

    INDEX `cso`(`cso`),
    INDEX `distrik`(`district`),
    INDEX `gender`(`gender`),
    INDEX `kecamatan`(`kecamatan`),
    INDEX `kelurahan`(`kelurahan`),
    INDEX `kode_cso`(`kode_cso`),
    INDEX `no`(`no`),
    INDEX `tgl_kontak`(`tgl_kontak`),
    INDEX `tipe_cbs`(`tipe_cbs`),
    INDEX `tipe_kd`(`tipe_kd`),
    INDEX `uic`(`uic`),
    INDEX `uuid`(`uuid`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form3` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `uic` VARCHAR(10) NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `umur` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NOT NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NULL,
    `category2` VARCHAR(200) NOT NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `district` VARCHAR(10) NULL,
    `kecamatan` VARCHAR(12) NULL,
    `kelurahan` VARCHAR(15) NULL,
    `kelurahan2` VARCHAR(15) NOT NULL,
    `manajemen_kasus` VARCHAR(100) NULL,
    `lokasi_kontak` VARCHAR(100) NULL,
    `phone` VARCHAR(50) NOT NULL,
    `phone_number` VARCHAR(15) NOT NULL,
    `ktp` VARCHAR(3) NULL,
    `ktp_ya` VARCHAR(100) NULL,
    `asuransi` VARCHAR(3) NULL,
    `asuransi_ya` VARCHAR(100) NULL,
    `dirujuk_oleh` VARCHAR(100) NULL,
    `dirujuk_oleh_detil` VARCHAR(200) NOT NULL,
    `layanan_perawatan` VARCHAR(200) NULL,
    `no_regnas` VARCHAR(50) NOT NULL,
    `mulai_art` VARCHAR(50) NOT NULL,
    `tgl_mulai_art` DATE NULL,
    `tgl_restart_arv` DATE NULL,
    `kategori_klien` VARCHAR(30) NOT NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NULL,
    `kode_parent_cbs` VARCHAR(100) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `tgl_review` DATE NOT NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `create_date` DATETIME(0) NOT NULL,
    `create_by` VARCHAR(50) NOT NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `quotes` VARCHAR(200) NOT NULL,
    `trash` INTEGER NOT NULL,

    INDEX `category`(`category`),
    INDEX `cso`(`cso`),
    INDEX `distrik`(`district`),
    INDEX `gender`(`gender`),
    INDEX `kecamatan`(`kecamatan`),
    INDEX `kelurahan`(`kelurahan`),
    INDEX `kode_cso`(`kode_cso`),
    INDEX `kps_sp`(`kps_sp`),
    INDEX `no`(`no`),
    INDEX `tgl_kontak`(`tgl_kontak`),
    INDEX `tgl_mulai_art`(`tgl_mulai_art`),
    INDEX `tipe_kd`(`tipe_kd`),
    INDEX `uic`(`uic`),
    INDEX `uuid`(`uuid`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form4` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `jumlah_kontak` INTEGER NOT NULL,
    `uic` VARCHAR(10) NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `tgl_lahir` DATE NOT NULL,
    `umur` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NOT NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NULL,
    `category2` VARCHAR(200) NOT NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `district` VARCHAR(10) NULL,
    `kecamatan` VARCHAR(12) NULL,
    `kelurahan` VARCHAR(15) NULL,
    `kelurahan2` VARCHAR(15) NOT NULL,
    `manajemen_kasus` VARCHAR(100) NULL,
    `lokasi_kontak` VARCHAR(100) NULL,
    `phone` VARCHAR(50) NOT NULL,
    `phone_number` VARCHAR(15) NOT NULL,
    `ktp` VARCHAR(3) NULL,
    `ktp_ya` VARCHAR(100) NULL,
    `asuransi` VARCHAR(3) NULL,
    `asuransi_ya` VARCHAR(100) NULL,
    `kunjungan` VARCHAR(25) NULL,
    `no_regnas` VARCHAR(50) NOT NULL,
    `jenis_arv` VARCHAR(25) NOT NULL,
    `kombinasi_arv` TEXT NOT NULL,
    `kombinasi_arv_lain` VARCHAR(200) NOT NULL,
    `tgl_art` DATE NULL,
    `tgl_art_pre` DATE NOT NULL,
    `belum_art` VARCHAR(50) NULL,
    `tgl_restart_arv` VARCHAR(50) NOT NULL,
    `tes_vl_terakhir` VARCHAR(50) NOT NULL,
    `syarat_tes_vl` VARCHAR(10) NOT NULL,
    `sudah_menjadwalkan_vl` VARCHAR(10) NOT NULL,
    `hasil_tes_vl` VARCHAR(30) NOT NULL,
    `nilai_tes_vl` INTEGER NOT NULL,
    `jadwal_tes_vl` VARCHAR(50) NOT NULL,
    `eligible_vl` VARCHAR(3) NOT NULL,
    `kesulitan_kepatuhan` VARCHAR(100) NULL,
    `kesulitan_kepatuhan_lainnya` VARCHAR(100) NOT NULL,
    `layanan_perawatan_hiv` VARCHAR(100) NULL,
    `tgl_terima_obat_arv` DATE NULL,
    `tgl_skedul_obat_arv` DATE NULL,
    `month_arv` INTEGER NOT NULL,
    `method_arv` VARCHAR(200) NOT NULL,
    `method_arv_other` VARCHAR(200) NOT NULL,
    `melewatkan_jadwal_kunjungan` VARCHAR(15) NULL,
    `alasan_melewatkan_jadwal_kunjungan` VARCHAR(100) NULL,
    `alasan_melewatkan_jadwal_kunjungan_lainnya` VARCHAR(200) NOT NULL,
    `art_lebih_satu_bulan` VARCHAR(10) NOT NULL,
    `art_lebih_satu_bulan_saat_ini` VARCHAR(10) NOT NULL,
    `ingin_didampingi_cbs` VARCHAR(15) NULL,
    `tergabung_kds` VARCHAR(15) NULL,
    `dukungan_keluarga` VARCHAR(15) NULL,
    `memberitahu_cd4` VARCHAR(15) NULL,
    `nilai_cd4` VARCHAR(15) NULL,
    `perubahan_berat_badan` VARCHAR(15) NULL,
    `mengalami_gejala_tb` VARCHAR(200) NOT NULL,
    `pernah_tes_tb` VARCHAR(5) NOT NULL,
    `beritahu_hasil` VARCHAR(10) NOT NULL,
    `hasil_tes_tb` VARCHAR(10) NOT NULL,
    `status_pengobatan_tb` VARCHAR(25) NOT NULL,
    `tpt` VARCHAR(25) NOT NULL,
    `tpt_lengkap` VARCHAR(10) NOT NULL,
    `tgl_tpt_lengkap` DATE NOT NULL,
    `pengobatan_penyakit_lain` VARCHAR(50) NULL,
    `nama_penyakit_lain` VARCHAR(50) NULL,
    `menerima_pengobatan` VARCHAR(15) NULL,
    `janji_temu_cbs` VARCHAR(15) NULL,
    `mengalami_kekerasan` VARCHAR(15) NULL,
    `rujukan_aeo` VARCHAR(10) NOT NULL,
    `emoji_perasaan_hidup` VARCHAR(15) NULL,
    `masih_membutuhkan_cbs` VARCHAR(25) NOT NULL,
    `pencegahan_hiv` VARCHAR(100) NULL,
    `material_pencegahan` VARCHAR(3) NULL,
    `media_kie` VARCHAR(3) NULL,
    `kartu_kontak_cbsplus` VARCHAR(3) NULL,
    `kartu_rujukan_kds` VARCHAR(3) NULL,
    `transportasi` VARCHAR(15) NOT NULL,
    `rujukan_layanan_lain` VARCHAR(3) NULL,
    `rujukan_layanan_lain_sebutkan` VARCHAR(100) NULL,
    `jumlah_jarum_suntik` BIGINT NOT NULL,
    `jumlah_kondom` BIGINT NOT NULL,
    `jumlah_pelicin` BIGINT NOT NULL,
    `jumlah_media_kie` BIGINT NOT NULL,
    `bersedia_index_testing` VARCHAR(15) NULL,
    `eligible_index_testing` VARCHAR(3) NOT NULL,
    `puas_kualitas_perawatan_layanan` VARCHAR(15) NULL,
    `puas_kualitas_perawatan_komunitas` VARCHAR(15) NULL,
    `rekomendasi` VARCHAR(50) NULL,
    `rencana_bertemu_lagi` VARCHAR(15) NULL,
    `tgl_bertemu_lagi` DATE NULL,
    `form5_lengkap` VARCHAR(20) NULL,
    `transisi_form4b` VARCHAR(20) NULL,
    `transisi_form4c` VARCHAR(20) NOT NULL,
    `form_terminasi` VARCHAR(15) NOT NULL,
    `menyelesaikan_layanan_cbs` VARCHAR(25) NOT NULL,
    `rujukan_diberikan` VARCHAR(50) NULL,
    `rujukan_diberikan_lain` VARCHAR(200) NOT NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NULL,
    `kode_parent_cbs` VARCHAR(100) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `form` VARCHAR(5) NOT NULL,
    `tgl_review` DATE NOT NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `create_date` DATETIME(0) NOT NULL,
    `create_by` VARCHAR(50) NOT NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `trash` INTEGER NOT NULL,

    INDEX `category`(`category`),
    INDEX `district`(`district`),
    INDEX `gender`(`gender`),
    INDEX `kps_sp`(`kps_sp`),
    INDEX `no`(`no`),
    INDEX `rujukan_diberikan`(`rujukan_diberikan`, `kode_nama_cbs`, `kode_cso`, `form`, `validated`, `trash`),
    INDEX `syarat_tes_vl`(`syarat_tes_vl`, `jadwal_tes_vl`, `layanan_perawatan_hiv`, `mengalami_gejala_tb`, `tpt`, `tgl_tpt_lengkap`, `bersedia_index_testing`, `eligible_index_testing`),
    INDEX `tes_vl_terakhir`(`tes_vl_terakhir`),
    INDEX `tgl_art`(`tgl_art`),
    INDEX `tgl_kontak`(`tgl_kontak`),
    INDEX `tgl_restart_arv`(`tgl_restart_arv`),
    INDEX `tgl_terima_obat_arv`(`tgl_terima_obat_arv`),
    INDEX `uic`(`uic`),
    INDEX `uuid`(`uuid`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form5` (
    `no` INTEGER NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `uic` VARCHAR(10) NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `umur` INTEGER NULL,
    `kps_sp` VARCHAR(15) NOT NULL,
    `gender` VARCHAR(15) NULL,
    `category` VARCHAR(20) NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `district` VARCHAR(50) NULL,
    `kecamatan` VARCHAR(12) NOT NULL,
    `kelurahan` VARCHAR(15) NOT NULL,
    `manajemen_kasus` VARCHAR(50) NULL,
    `lokasi_kontak` VARCHAR(100) NOT NULL,
    `referred_form` VARCHAR(50) NULL,
    `relationship1` VARCHAR(30) NULL,
    `partner_gender1` VARCHAR(15) NULL,
    `partner_age1` SMALLINT NULL,
    `partner_age1_month` SMALLINT NOT NULL,
    `resiko_kekerasan1` VARCHAR(50) NULL,
    `lanjut1_np` VARCHAR(15) NOT NULL,
    `lanjut1_form8` VARCHAR(15) NOT NULL,
    `tipe_rujukan1` VARCHAR(50) NULL,
    `nama1` VARCHAR(30) NOT NULL,
    `phone1` VARCHAR(15) NOT NULL,
    `contacted1` VARCHAR(5) NOT NULL,
    `relationship2` VARCHAR(30) NULL,
    `partner_gender2` VARCHAR(15) NULL,
    `partner_age2` SMALLINT NULL,
    `partner_age2_month` SMALLINT NOT NULL,
    `resiko_kekerasan2` VARCHAR(50) NULL,
    `lanjut2_np` VARCHAR(15) NOT NULL,
    `lanjut2_form8` VARCHAR(15) NOT NULL,
    `tipe_rujukan2` VARCHAR(50) NULL,
    `nama2` VARCHAR(30) NOT NULL,
    `phone2` VARCHAR(15) NOT NULL,
    `contacted2` VARCHAR(5) NOT NULL,
    `relationship3` VARCHAR(30) NULL,
    `partner_gender3` VARCHAR(15) NULL,
    `partner_age3` SMALLINT NULL,
    `partner_age3_month` SMALLINT NOT NULL,
    `resiko_kekerasan3` VARCHAR(50) NULL,
    `lanjut3_np` VARCHAR(15) NOT NULL,
    `lanjut3_form8` VARCHAR(15) NOT NULL,
    `tipe_rujukan3` VARCHAR(50) NULL,
    `nama3` VARCHAR(30) NOT NULL,
    `phone3` VARCHAR(15) NOT NULL,
    `contacted3` VARCHAR(5) NOT NULL,
    `relationship4` VARCHAR(30) NULL,
    `partner_gender4` VARCHAR(15) NULL,
    `partner_age4` SMALLINT NULL,
    `partner_age4_month` SMALLINT NOT NULL,
    `resiko_kekerasan4` VARCHAR(50) NULL,
    `lanjut4_np` VARCHAR(15) NOT NULL,
    `lanjut4_form8` VARCHAR(15) NOT NULL,
    `tipe_rujukan4` VARCHAR(50) NULL,
    `nama4` VARCHAR(30) NOT NULL,
    `phone4` VARCHAR(15) NOT NULL,
    `contacted4` VARCHAR(5) NOT NULL,
    `relationship5` VARCHAR(30) NULL,
    `partner_gender5` VARCHAR(15) NULL,
    `partner_age5` SMALLINT NULL,
    `partner_age5_month` SMALLINT NOT NULL,
    `resiko_kekerasan5` VARCHAR(50) NULL,
    `lanjut5_np` VARCHAR(15) NOT NULL,
    `lanjut5_form8` VARCHAR(15) NOT NULL,
    `tipe_rujukan5` VARCHAR(50) NULL,
    `nama5` VARCHAR(30) NOT NULL,
    `phone5` VARCHAR(15) NOT NULL,
    `contacted5` VARCHAR(5) NOT NULL,
    `list` INTEGER NOT NULL,
    `tgl_kontak1` DATE NOT NULL,
    `tgl_kontak2` DATE NOT NULL,
    `tgl_kontak3` DATE NOT NULL,
    `tgl_kontak4` DATE NOT NULL,
    `tgl_kontak5` DATE NOT NULL,
    `hasil1` VARCHAR(25) NOT NULL,
    `hasil2` VARCHAR(25) NOT NULL,
    `hasil3` VARCHAR(25) NOT NULL,
    `hasil4` VARCHAR(25) NOT NULL,
    `hasil5` VARCHAR(25) NOT NULL,
    `skrining1` VARCHAR(5) NOT NULL,
    `skrining2` VARCHAR(5) NOT NULL,
    `skrining3` VARCHAR(5) NOT NULL,
    `skrining4` VARCHAR(5) NOT NULL,
    `skrining5` VARCHAR(5) NOT NULL,
    `rujukan1` VARCHAR(25) NOT NULL,
    `rujukan2` VARCHAR(25) NOT NULL,
    `rujukan3` VARCHAR(25) NOT NULL,
    `rujukan4` VARCHAR(25) NOT NULL,
    `rujukan5` VARCHAR(25) NOT NULL,
    `uic1` VARCHAR(10) NOT NULL,
    `uic2` VARCHAR(10) NOT NULL,
    `uic3` VARCHAR(10) NOT NULL,
    `uic4` VARCHAR(10) NOT NULL,
    `uic5` VARCHAR(10) NOT NULL,
    `fasyankes1` VARCHAR(30) NOT NULL,
    `fasyankes2` VARCHAR(30) NOT NULL,
    `fasyankes3` VARCHAR(30) NOT NULL,
    `fasyankes4` VARCHAR(30) NOT NULL,
    `fasyankes5` VARCHAR(30) NOT NULL,
    `jumlah_slip` VARCHAR(3) NULL,
    `nama_cbs_plus` VARCHAR(50) NULL,
    `jumlah_kartu_cbs` VARCHAR(3) NULL,
    `rencana_bertemu_lagi` VARCHAR(15) NULL,
    `tgl_bertemu_lagi` DATE NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NULL,
    `kode_parent_cbs` VARCHAR(100) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `tgl_review` DATE NOT NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `create_date` DATETIME(0) NOT NULL,
    `create_by` VARCHAR(50) NOT NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `trash` INTEGER NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form5a` (
    `no` INTEGER NOT NULL,
    `uuid` VARCHAR(100) NULL,
    `id` VARCHAR(25) NOT NULL,
    `num` INTEGER NOT NULL,
    `fid` VARCHAR(25) NULL,
    `tgl_kontak` DATE NULL,
    `uic` VARCHAR(15) NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `umur` INTEGER NULL,
    `kps_sp` VARCHAR(15) NOT NULL,
    `gender` VARCHAR(15) NULL,
    `category` VARCHAR(20) NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `district` VARCHAR(50) NULL,
    `kecamatan` VARCHAR(12) NOT NULL,
    `kelurahan` VARCHAR(15) NOT NULL,
    `manajemen_kasus` VARCHAR(50) NULL,
    `lokasi_kontak` VARCHAR(100) NOT NULL,
    `referred_form` VARCHAR(50) NULL,
    `pn_relation` VARCHAR(30) NULL,
    `pn_gender` VARCHAR(15) NULL,
    `pn_age` SMALLINT NULL,
    `pn_age_month` SMALLINT NULL,
    `pn_resiko` VARCHAR(50) NULL,
    `pn_aeo` VARCHAR(15) NULL,
    `pn_form8` VARCHAR(15) NULL,
    `pn_tipe_rujukan` VARCHAR(50) NULL,
    `pn_nama` VARCHAR(30) NULL,
    `pn_phone` VARCHAR(15) NULL,
    `contacted` VARCHAR(5) NULL,
    `list` INTEGER NOT NULL,
    `pn_tgl_kontak` DATE NOT NULL,
    `pn_hasil` VARCHAR(25) NOT NULL,
    `pn_skrining` VARCHAR(5) NOT NULL,
    `pn_rujukan` VARCHAR(25) NOT NULL,
    `pn_uic` VARCHAR(10) NOT NULL,
    `pn_fasyankes` VARCHAR(30) NOT NULL,
    `jumlah_slip` VARCHAR(3) NULL,
    `nama_cbs_plus` VARCHAR(50) NULL,
    `jumlah_kartu_cbs` VARCHAR(3) NULL,
    `rencana_bertemu_lagi` VARCHAR(15) NULL,
    `tgl_bertemu_lagi` DATE NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NULL,
    `kode_parent_cbs` VARCHAR(100) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `tgl_review` DATE NOT NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `create_date` DATETIME(0) NOT NULL,
    `create_by` VARCHAR(50) NOT NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `trash` INTEGER NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form6` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `uic` VARCHAR(10) NULL,
    `nik` VARCHAR(16) NOT NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `gender_parent` VARCHAR(15) NOT NULL,
    `category_parent` VARCHAR(50) NOT NULL,
    `tipe_rujukan` VARCHAR(50) NOT NULL,
    `referred_form` VARCHAR(10) NOT NULL,
    `umur` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NOT NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `district` VARCHAR(10) NULL,
    `kecamatan` VARCHAR(10) NOT NULL,
    `kelurahan` VARCHAR(15) NOT NULL,
    `kode_layanan` VARCHAR(30) NOT NULL,
    `nama_layanan` VARCHAR(100) NULL,
    `alamat_layanan` VARCHAR(100) NULL,
    `district_layanan` VARCHAR(100) NOT NULL,
    `hotspot` VARCHAR(200) NOT NULL,
    `petugas` VARCHAR(100) NOT NULL,
    `slip` VARCHAR(200) NULL,
    `slip_tes` VARCHAR(200) NOT NULL,
    `ma_ltfu` VARCHAR(15) NOT NULL,
    `tes_hiv` VARCHAR(5) NULL,
    `tes_konfirmasi` VARCHAR(10) NOT NULL,
    `status_hiv` VARCHAR(15) NULL,
    `register` VARCHAR(5) NULL,
    `inisiasi_arv` DATE NULL,
    `refill_arv` DATE NULL,
    `restart_arv` DATE NULL,
    `tes_vl` VARCHAR(5) NULL,
    `hasil_vl` VARCHAR(50) NULL,
    `tes_cd4` VARCHAR(5) NULL,
    `hasil_cd4` VARCHAR(50) NULL,
    `stb` VARCHAR(5) NOT NULL,
    `tes_tb` VARCHAR(5) NULL,
    `pengobatan_tb` VARCHAR(5) NULL,
    `tpt` VARCHAR(10) NOT NULL,
    `ims` VARCHAR(5) NULL,
    `inisiasi_prep` VARCHAR(5) NOT NULL,
    `refil_prep` VARCHAR(5) NOT NULL,
    `lainnya` VARCHAR(5) NULL,
    `catatan` VARCHAR(200) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NULL,
    `kode_parent_cbs` VARCHAR(100) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `form` VARCHAR(5) NOT NULL,
    `tgl_review` DATE NOT NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `create_date` DATETIME(0) NOT NULL,
    `create_by` VARCHAR(50) NOT NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `trash` INTEGER NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form7` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `uic` VARCHAR(10) NULL,
    `umur` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NOT NULL,
    `category2` VARCHAR(200) NOT NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `district` VARCHAR(10) NOT NULL,
    `kecamatan` VARCHAR(12) NOT NULL,
    `kelurahan` VARCHAR(15) NOT NULL,
    `lokasi_kontak` VARCHAR(100) NULL,
    `phone` VARCHAR(30) NOT NULL,
    `phone_number` VARCHAR(15) NOT NULL,
    `kategori` VARCHAR(15) NULL,
    `dirujuk_oleh` VARCHAR(100) NULL,
    `cbs` VARCHAR(10) NOT NULL,
    `fasyankes` VARCHAR(100) NULL,
    `frekuensi` INTEGER NOT NULL,
    `tgl_pertama_inisiasi` DATE NOT NULL,
    `tgl_akhir_akses` DATE NOT NULL,
    `nomor_regnas` VARCHAR(25) NOT NULL,
    `mekanisme` VARCHAR(20) NULL,
    `mekanisme_detail` VARCHAR(50) NOT NULL,
    `missed_appointment` VARCHAR(10) NOT NULL,
    `missed_cause` VARCHAR(100) NOT NULL,
    `missed_cause_other` VARCHAR(100) NOT NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `hasil_telusur` VARCHAR(20) NULL,
    `pendamping_rujukan` VARCHAR(10) NULL,
    `transportasi` VARCHAR(5) NULL,
    `bertemu_lagi` VARCHAR(10) NULL,
    `penelusur` VARCHAR(100) NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NULL,
    `tgl_review` DATE NULL,
    `create_date` DATETIME(0) NULL,
    `create_by` VARCHAR(50) NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `trash` BOOLEAN NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form7bscreening` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `form1` VARCHAR(5) NOT NULL,
    `asal_form` VARCHAR(15) NOT NULL,
    `uic` VARCHAR(10) NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `tgl_lahir` DATE NOT NULL,
    `umur` INTEGER NOT NULL,
    `umur_bulan` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NOT NULL,
    `category2` VARCHAR(200) NOT NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `klien_adalah` VARCHAR(25) NOT NULL,
    `district` VARCHAR(10) NOT NULL,
    `kecamatan` VARCHAR(12) NOT NULL,
    `kelurahan` VARCHAR(15) NOT NULL,
    `lokasi_kontak` VARCHAR(100) NULL,
    `lokasi_kontak_lain` VARCHAR(100) NOT NULL,
    `phone` VARCHAR(30) NOT NULL,
    `phone_number` VARCHAR(15) NOT NULL,
    `ktp` VARCHAR(5) NOT NULL,
    `ktp_ya` VARCHAR(100) NOT NULL,
    `ktp_nik` VARCHAR(20) NOT NULL,
    `pernah_tes_hiv` VARCHAR(50) NULL,
    `pernah_skrining` VARCHAR(50) NULL,
    `peraga_langsung` VARCHAR(100) NOT NULL,
    `alat_bantu_kerja` VARCHAR(100) NULL,
    `skrining_sekarang` VARCHAR(100) NOT NULL,
    `skrining_60_menit` VARCHAR(5) NOT NULL,
    `tempat_layak_skrining` VARCHAR(5) NOT NULL,
    `skrining_sendiri` VARCHAR(5) NOT NULL,
    `kontak_skrining_rumah` VARCHAR(25) NULL,
    `kontak_skrining_detail` VARCHAR(50) NOT NULL,
    `asisten_virtual` VARCHAR(5) NOT NULL,
    `asisten_virtual_ya` VARCHAR(50) NOT NULL,
    `asisten_virtual_detail` VARCHAR(50) NOT NULL,
    `panggilan_24jam` VARCHAR(50) NOT NULL,
    `panggilan_48jam` VARCHAR(50) NOT NULL,
    `kesulitan_skrining` VARCHAR(100) NOT NULL,
    `kesulitan_skrining_ya` VARCHAR(100) NULL,
    `membagi_hasil` VARCHAR(5) NULL,
    `membagi_hasil_ya` VARCHAR(25) NULL,
    `alat_skrining` INTEGER NOT NULL,
    `slip_rujukan_dibantu` VARCHAR(5) NULL,
    `slip_rujukan_tanpa_dibantu` VARCHAR(5) NOT NULL,
    `media_kie` VARCHAR(5) NOT NULL,
    `kartu_kontak_cbs` VARCHAR(5) NOT NULL,
    `slip_2pn` VARCHAR(5) NOT NULL,
    `menolak_dirujuk` VARCHAR(5) NOT NULL,
    `tidak_skrining` VARCHAR(5) NOT NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `nama_cbs_plus` VARCHAR(50) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NOT NULL,
    `kode_parent_cbs` VARCHAR(100) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NULL,
    `tgl_review` DATE NULL,
    `create_date` DATETIME(0) NULL,
    `create_by` VARCHAR(50) NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `trash` BOOLEAN NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form7screening` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `form1` VARCHAR(5) NOT NULL,
    `upstatus` VARCHAR(5) NULL,
    `form5b` VARCHAR(5) NULL,
    `asal_form` VARCHAR(15) NOT NULL,
    `uic` VARCHAR(10) NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `tgl_lahir` DATE NOT NULL,
    `umur` INTEGER NOT NULL,
    `umur_bulan` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NOT NULL,
    `category2` VARCHAR(200) NOT NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `klien_adalah` VARCHAR(25) NOT NULL,
    `district` VARCHAR(10) NOT NULL,
    `kecamatan` VARCHAR(12) NOT NULL,
    `kelurahan` VARCHAR(15) NOT NULL,
    `lokasi_kontak` VARCHAR(100) NULL,
    `lokasi_kontak_lain` VARCHAR(100) NOT NULL,
    `phone` VARCHAR(30) NOT NULL,
    `phone_number` VARCHAR(15) NOT NULL,
    `ktp` VARCHAR(5) NOT NULL,
    `ktp_ya` VARCHAR(100) NOT NULL,
    `ktp_nik` VARCHAR(20) NOT NULL,
    `pernah_tes_hiv` VARCHAR(50) NULL,
    `pernah_skrining` VARCHAR(50) NULL,
    `peraga_langsung` VARCHAR(100) NOT NULL,
    `alat_bantu_kerja` VARCHAR(100) NULL,
    `skrining_sekarang` VARCHAR(100) NOT NULL,
    `skrining_60_menit` VARCHAR(5) NOT NULL,
    `tempat_layak_skrining` VARCHAR(5) NOT NULL,
    `skrining_sendiri` VARCHAR(5) NOT NULL,
    `kontak_skrining_rumah` VARCHAR(25) NULL,
    `kontak_skrining_detail` VARCHAR(50) NOT NULL,
    `asisten_virtual` VARCHAR(5) NOT NULL,
    `asisten_virtual_ya` VARCHAR(50) NOT NULL,
    `asisten_virtual_detail` VARCHAR(50) NOT NULL,
    `panggilan_24jam` VARCHAR(50) NOT NULL,
    `panggilan_48jam` VARCHAR(50) NOT NULL,
    `kesulitan_skrining` VARCHAR(100) NOT NULL,
    `kesulitan_skrining_ya` VARCHAR(100) NULL,
    `membagi_hasil` VARCHAR(5) NULL,
    `membagi_hasil_ya` VARCHAR(25) NULL,
    `alat_skrining` INTEGER NOT NULL,
    `slip_rujukan_dibantu` VARCHAR(5) NULL,
    `slip_rujukan_tanpa_dibantu` VARCHAR(5) NOT NULL,
    `media_kie` VARCHAR(5) NOT NULL,
    `kartu_kontak_cbs` VARCHAR(5) NOT NULL,
    `slip_2pn` VARCHAR(5) NOT NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `nama_cbs_plus` VARCHAR(50) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NOT NULL,
    `kode_parent_cbs` VARCHAR(100) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NULL,
    `tgl_review` DATE NULL,
    `create_date` DATETIME(0) NULL,
    `create_by` VARCHAR(50) NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `trash` BOOLEAN NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_form8` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `uic` VARCHAR(10) NOT NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `umur` INTEGER NOT NULL,
    `kps_sp` VARCHAR(25) NOT NULL,
    `gender` VARCHAR(25) NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `tipe_kd` VARCHAR(50) NOT NULL,
    `district` VARCHAR(10) NOT NULL,
    `kecamatan` VARCHAR(12) NOT NULL,
    `kelurahan` VARCHAR(15) NOT NULL,
    `nama_petugas` VARCHAR(100) NOT NULL,
    `jabatan_petugas` VARCHAR(100) NOT NULL,
    `jabatan_petugas_lain` VARCHAR(100) NOT NULL,
    `lembaga_petugas` VARCHAR(100) NOT NULL,
    `tanggal_formulir` DATE NOT NULL,
    `lokasi_pengungkapan` VARCHAR(50) NOT NULL,
    `lokasi_pengungkapan_lain` VARCHAR(100) NOT NULL,
    `kekerasan_diungkap_anonim` VARCHAR(10) NOT NULL,
    `gender_lain` VARCHAR(50) NOT NULL,
    `gender_lahir` VARCHAR(25) NOT NULL,
    `gender_lahir_lain` VARCHAR(50) NOT NULL,
    `tipe_populasi` VARCHAR(25) NOT NULL,
    `tipe_populasi_lain` VARCHAR(100) NOT NULL,
    `tipe_kd_lain` VARCHAR(100) NOT NULL,
    `jenis_layanan_diakses` VARCHAR(25) NOT NULL,
    `jenis_layanan_diakses_lain` VARCHAR(100) NOT NULL,
    `tanggal_kekerasan_sebelumnya` DATE NOT NULL,
    `lokasi_kekerasan` VARCHAR(200) NOT NULL,
    `kapan_pengungkapan_kejadian` VARCHAR(200) NOT NULL,
    `jenis_kekerasan_terjadi` VARCHAR(200) NOT NULL,
    `jenis_kekerasan_ham_terjadi` VARCHAR(200) NOT NULL,
    `jenis_kekerasan_lain_terjadi` VARCHAR(200) NOT NULL,
    `deskripsi_kekerasan` TEXT NOT NULL,
    `pelaku_kekerasan` VARCHAR(200) NOT NULL,
    `pelaku_petugas_layanan` VARCHAR(100) NOT NULL,
    `pelaku_petugas_penjangkau` VARCHAR(100) NOT NULL,
    `pelaku_kekerasan_lainnya` VARCHAR(200) NOT NULL,
    `kekerasan_akibat_layanan` VARCHAR(100) NOT NULL,
    `kekerasan_akibat_layanan_lain` VARCHAR(200) NOT NULL,
    `kekerasan_terkait_psbb` VARCHAR(25) NOT NULL,
    `tanggapan_awal_pengungkapan` VARCHAR(200) NOT NULL,
    `nama_petugas_bagian2` VARCHAR(100) NOT NULL,
    `jabatan_petugas_bagian2` VARCHAR(100) NOT NULL,
    `jabatan_petugas_bagian2_lain` VARCHAR(200) NOT NULL,
    `instansi_petugas_bagian2` VARCHAR(100) NOT NULL,
    `layak_mendapatkan_pep` VARCHAR(25) NOT NULL,
    `layak_mendapatkan_kontrasepsi` VARCHAR(25) NOT NULL,
    `asesmen_yang_ditawarkan` TEXT NULL,
    `pengobatan_luka` TEXT NULL,
    `rapid_tes_hiv` TEXT NULL,
    `post_exposure_prophylaxis` TEXT NULL,
    `pengobatan_skrining_ims` TEXT NULL,
    `kontrasepsi_darurat` TEXT NULL,
    `konseling_psikososial` TEXT NULL,
    `kesehatan_mental` TEXT NULL,
    `vaksin_tetanus` TEXT NULL,
    `inisiasi_art` TEXT NULL,
    `rujukan_prep` TEXT NULL,
    `dukungan_psikososial` TEXT NULL,
    `bantuan_hukum` TEXT NULL,
    `intervensi_penegakan_hukum` TEXT NULL,
    `perlindungan_anak` TEXT NULL,
    `pemberdayaan_ekonomi` TEXT NULL,
    `rumah_singgah_sementara` TEXT NULL,
    `rujukan_yang_diberikan_lainnya` TEXT NULL,
    `hasil_rujukan_yang_diberikan_lainnya` TEXT NULL,
    `apakah_prep_diberikan` VARCHAR(15) NOT NULL,
    `tes_hiv_3bulan_setelahnya` VARCHAR(15) NOT NULL,
    `tidak_lanjut_diberikan` TEXT NULL,
    `nama_petugas_investigasi` VARCHAR(100) NOT NULL,
    `jabatan_petugas_investigasi` VARCHAR(200) NOT NULL,
    `ringkasan_temuan` TEXT NOT NULL,
    `tindak_lanjut_akan_datang` TEXT NOT NULL,
    `diselesaikan_masalah_ini` VARCHAR(15) NOT NULL,
    `tindak_lanjut_tidak_diselesaikan` TEXT NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NOT NULL,
    `cso` VARCHAR(200) NOT NULL,
    `kode_cso` VARCHAR(25) NOT NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `created_date` DATETIME(0) NULL,
    `created_by` VARCHAR(50) NOT NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `approved` VARCHAR(1) NOT NULL,
    `trash` INTEGER NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_kelurahan` (
    `daerah_id` INTEGER NOT NULL,
    `site_id` VARCHAR(100) NOT NULL,
    `daerah_kode` VARCHAR(100) NOT NULL,
    `daerah_titel` VARCHAR(200) NOT NULL,
    `daerah_alias` VARCHAR(200) NOT NULL,
    `daerah_paren` VARCHAR(100) NOT NULL,
    `daerah_tipe` VARCHAR(100) NOT NULL,
    `daerah_latitude` VARCHAR(10) NOT NULL,
    `daerah_longitude` VARCHAR(10) NOT NULL,
    `create_by` VARCHAR(100) NOT NULL,
    `modify_by` VARCHAR(100) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_kitscreening` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `tgl_kontak` DATE NOT NULL,
    `tgl_distribusi` DATE NULL,
    `distribusi` INTEGER NOT NULL,
    `tgl_periksa` DATE NULL,
    `rusak` INTEGER NOT NULL,
    `diterima` INTEGER NOT NULL,
    `akumulasi` INTEGER NOT NULL,
    `dipakai` INTEGER NOT NULL,
    `stok` INTEGER NOT NULL,
    `kode_nama_cbs` VARCHAR(50) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NULL,
    `create_date` DATETIME(0) NULL,
    `create_by` VARCHAR(50) NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `trash` INTEGER NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_option` (
    `op_id` INTEGER NOT NULL,
    `site_id` VARCHAR(2) NOT NULL,
    `op_titel` VARCHAR(200) NOT NULL,
    `op_alias` VARCHAR(200) NOT NULL,
    `op_kode` VARCHAR(15) NOT NULL,
    `op_data` VARCHAR(200) NOT NULL,
    `op_paren` INTEGER NOT NULL,
    `op_tipe` VARCHAR(50) NOT NULL,
    `create_by` VARCHAR(30) NOT NULL,
    `modify_by` VARCHAR(30) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_plhiv` (
    `id` INTEGER NOT NULL,
    `tested_id` INTEGER NULL,
    `uic` VARCHAR(10) NOT NULL,
    `kode_cso` VARCHAR(15) NOT NULL,
    `diagnosed_at` DATE NULL,
    `pn` VARCHAR(5) NULL,
    `confirmatory_test` VARCHAR(5) NULL,
    `registered_at` DATE NULL,
    `initiated_at` DATE NULL,
    `last_refill` DATE NULL,
    `next_refill` DATE NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_profil` (
    `id` INTEGER NOT NULL,
    `tgl_kontak` DATE NULL,
    `jumlah_kontak` INTEGER NOT NULL,
    `uic` VARCHAR(10) NULL,
    `nik` VARCHAR(16) NULL,
    `umur` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NOT NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NULL,
    `category2` VARCHAR(200) NOT NULL,
    `district` VARCHAR(10) NULL,
    `kecamatan` VARCHAR(12) NULL,
    `kelurahan` VARCHAR(15) NULL,
    `kelurahan2` VARCHAR(30) NOT NULL,
    `lokasi_kontak` VARCHAR(100) NULL,
    `phone` VARCHAR(20) NOT NULL,
    `phone_number` VARCHAR(15) NOT NULL,
    `ktp` VARCHAR(3) NULL,
    `ktp_ya` VARCHAR(100) NULL,
    `asuransi` VARCHAR(3) NULL,
    `asuransi_ya` VARCHAR(100) NULL,
    `tahu_status_hiv` VARCHAR(15) NULL,
    `klien_adalah` VARCHAR(50) NOT NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `created_by` VARCHAR(50) NULL,
    `created_at` DATETIME(0) NULL,
    `updated_at` DATETIME(0) NULL,
    `deleted_at` DATETIME(0) NULL,
    `trash` INTEGER NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_target_2024` (
    `no` INTEGER NOT NULL,
    `id` VARCHAR(50) NOT NULL,
    `mulai` DATE NOT NULL,
    `akhir` DATE NOT NULL,
    `indikator` VARCHAR(50) NOT NULL,
    `tipe_data` VARCHAR(10) NOT NULL,
    `angka` INTEGER NOT NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `create_by` VARCHAR(30) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_by` VARCHAR(30) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL,
    `trash` INTEGER NULL DEFAULT 0
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_termination` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `jumlah_kontak` INTEGER NOT NULL,
    `uic` VARCHAR(10) NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `umur` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NOT NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NULL,
    `category2` VARCHAR(200) NOT NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `district` VARCHAR(10) NULL,
    `kecamatan` VARCHAR(12) NULL,
    `kelurahan` VARCHAR(15) NULL,
    `phone` VARCHAR(50) NOT NULL,
    `phone_number` VARCHAR(15) NOT NULL,
    `form_cbs` VARCHAR(50) NULL,
    `tindak_lanjut` VARCHAR(100) NULL,
    `alasan` VARCHAR(100) NULL,
    `alasan_lainnya` VARCHAR(200) NULL,
    `cbs_baru` VARCHAR(50) NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `kode_nama_cbs` VARCHAR(50) NULL,
    `kode_parent_cbs` VARCHAR(50) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `form` VARCHAR(5) NOT NULL,
    `tgl_review` DATE NOT NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `create_date` DATETIME(0) NOT NULL,
    `create_by` VARCHAR(50) NOT NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `trash` INTEGER NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_transition` (
    `no` BIGINT NOT NULL,
    `uuid` VARCHAR(200) NOT NULL,
    `id` VARCHAR(100) NOT NULL,
    `tgl_kontak` DATE NULL,
    `uic` VARCHAR(10) NULL,
    `uic_parent` VARCHAR(10) NOT NULL,
    `tgl_lahir` DATE NOT NULL,
    `umur` INTEGER NOT NULL,
    `kps_sp` VARCHAR(10) NOT NULL,
    `gender` VARCHAR(12) NULL,
    `category` VARCHAR(50) NULL,
    `category2` VARCHAR(200) NOT NULL,
    `tipe_kd` VARCHAR(15) NOT NULL,
    `district` VARCHAR(10) NULL,
    `kecamatan` VARCHAR(12) NULL,
    `kelurahan` VARCHAR(15) NULL,
    `phone` VARCHAR(50) NOT NULL,
    `phone_number` VARCHAR(15) NOT NULL,
    `status_odha` VARCHAR(25) NOT NULL,
    `form_cbs` VARCHAR(15) NOT NULL,
    `jenis_arv` VARCHAR(25) NOT NULL,
    `kombinasi_arv` TEXT NOT NULL,
    `kombinasi_arv_lain` VARCHAR(200) NOT NULL,
    `tgl_art` DATE NULL,
    `belum_art` VARCHAR(50) NULL,
    `tes_vl_terakhir` VARCHAR(50) NOT NULL,
    `syarat_tes_vl` VARCHAR(10) NOT NULL,
    `sudah_menjadwalkan_vl` VARCHAR(10) NOT NULL,
    `hasil_tes_vl` VARCHAR(30) NOT NULL,
    `nilai_tes_vl` INTEGER NOT NULL,
    `jadwal_tes_vl` VARCHAR(50) NOT NULL,
    `tindak_lanjut` VARCHAR(50) NOT NULL,
    `lembaga_baru` VARCHAR(50) NOT NULL,
    `petugas_baru` VARCHAR(50) NOT NULL,
    `kontak_baru` VARCHAR(50) NOT NULL,
    `layanan_pdp` VARCHAR(50) NOT NULL,
    `rujuk_kds` VARCHAR(50) NOT NULL,
    `lembaga_kds` VARCHAR(25) NOT NULL,
    `pindah_layanan` VARCHAR(50) NOT NULL,
    `tindak_lanjut_lainnya` VARCHAR(50) NOT NULL,
    `form_entri` VARCHAR(10) NOT NULL,
    `kode_nama_cbs` VARCHAR(100) NULL,
    `kode_parent_cbs` VARCHAR(100) NOT NULL,
    `tipe_cbs` VARCHAR(200) NOT NULL,
    `cso` VARCHAR(200) NULL,
    `kode_cso` VARCHAR(10) NOT NULL,
    `form` VARCHAR(5) NOT NULL,
    `tgl_review` DATE NOT NULL,
    `validated` DATETIME(0) NULL,
    `reported` DATETIME(0) NULL,
    `create_date` DATETIME(0) NOT NULL,
    `create_by` VARCHAR(50) NOT NULL,
    `modify_date` DATETIME(0) NULL,
    `modify_by` VARCHAR(50) NOT NULL,
    `trash` INTEGER NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_user_log` (
    `user_log_id` INTEGER NOT NULL,
    `site_id` VARCHAR(100) NOT NULL,
    `user_id` INTEGER NOT NULL,
    `duration` INTEGER NOT NULL,
    `login` DATETIME(0) NOT NULL,
    `last` DATETIME(0) NOT NULL,
    `logout` DATETIME(0) NOT NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_users` (
    `user_id` INTEGER NOT NULL,
    `user_uuid` VARCHAR(200) NOT NULL,
    `site_id` VARCHAR(2) NOT NULL,
    `user_login` VARCHAR(100) NOT NULL,
    `user_login_old` VARCHAR(200) NOT NULL,
    `user_pass` VARCHAR(200) NOT NULL,
    `user_pass2` VARCHAR(200) NOT NULL,
    `user_first` VARCHAR(200) NOT NULL,
    `user_last` VARCHAR(200) NOT NULL,
    `user_gender` VARCHAR(100) NOT NULL,
    `user_tmp_lahir` VARCHAR(100) NOT NULL,
    `user_tgl_lahir` DATE NULL,
    `user_level_instansi` VARCHAR(100) NOT NULL,
    `user_type` VARCHAR(100) NOT NULL,
    `user_implementor` VARCHAR(50) NOT NULL,
    `prov_kode` VARCHAR(15) NOT NULL,
    `kab_kode` VARCHAR(15) NOT NULL,
    `kec_kode` VARCHAR(15) NOT NULL,
    `user_alamat` VARCHAR(200) NOT NULL,
    `user_email` VARCHAR(200) NOT NULL,
    `user_wilayah` VARCHAR(15) NOT NULL,
    `user_telepon` VARCHAR(15) NOT NULL,
    `user_imei` VARCHAR(200) NOT NULL,
    `user_lama_kerja` VARCHAR(30) NOT NULL,
    `user_group` VARCHAR(5) NOT NULL,
    `user_group2` VARCHAR(3) NOT NULL,
    `user_mulai` DATE NOT NULL,
    `user_akhir` DATE NOT NULL,
    `user_perminggu` INTEGER NOT NULL,
    `user_renumerasi` VARCHAR(100) NOT NULL,
    `user_renumerasi_nilai` DECIMAL(10, 0) NOT NULL,
    `user_salary` DECIMAL(10, 0) NOT NULL,
    `user_stipend` DECIMAL(10, 0) NOT NULL,
    `user_transportasi` DECIMAL(10, 0) NOT NULL,
    `user_telekomunikasi` DECIMAL(10, 0) NOT NULL,
    `user_alat` VARCHAR(100) NOT NULL,
    `user_renumerasi_lain` VARCHAR(100) NOT NULL,
    `user_renumerasi_nilai_lain` VARCHAR(100) NOT NULL,
    `user_jam_kerja` INTEGER NOT NULL,
    `user_paren` VARCHAR(100) NOT NULL,
    `user_level` VARCHAR(100) NOT NULL,
    `user_permit` TEXT NOT NULL,
    `user_active` VARCHAR(1) NOT NULL,
    `user_display` VARCHAR(200) NOT NULL,
    `user_avatar` VARCHAR(200) NOT NULL,
    `utoken` VARCHAR(200) NOT NULL,
    `create_by` VARCHAR(30) NOT NULL,
    `create_date` DATETIME(0) NOT NULL,
    `modify_by` VARCHAR(30) NOT NULL,
    `modify_date` DATETIME(0) NOT NULL,
    `language` VARCHAR(15) NOT NULL,
    `trash` INTEGER NOT NULL,

    PRIMARY KEY (`user_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
