import { z, ZodType } from "zod";

export class UserValidation {
    static readonly REGISTER: ZodType = z.object({
        user_id: z.number().int(),
        user_uuid: z.string().max(200),
        site_id: z.string().max(2),
        user_login: z.string().max(100),
        user_login_old: z.string().max(200),
        user_pass: z.string().max(200),
        user_pass2: z.string().max(200),
        user_first: z.string().max(200),
        user_last: z.string().max(200),
        user_gender: z.string().max(100),
        user_tmp_lahir: z.string().max(100),
        user_tgl_lahir: z.date().optional(),
        user_level_instansi: z.string().max(100),
        user_type: z.string().max(100),
        user_implementor: z.string().max(50),
        prov_kode: z.string().max(15),
        kab_kode: z.string().max(15),
        kec_kode: z.string().max(15),
        user_alamat: z.string().max(200),
        user_email: z.string().email().max(200),
        user_wilayah: z.string().max(15),
        user_telepon: z.string().max(15),
        user_imei: z.string().max(200),
        user_lama_kerja: z.string().max(30),
        user_group: z.string().max(5),
        user_group2: z.string().max(3),
        user_mulai: z.date(),
        user_akhir: z.date(),
        user_perminggu: z.number().int(),
        user_renumerasi: z.string().max(100),
        user_renumerasi_nilai: z.number(),
        user_salary: z.number(),
        user_stipend: z.number(),
        user_transportasi: z.number(),
        user_telekomunikasi: z.number(),
        user_alat: z.string().max(100),
        user_renumerasi_lain: z.string().max(100),
        user_renumerasi_nilai_lain: z.string().max(100),
        user_jam_kerja: z.number().int(),
        user_paren: z.string().max(100),
        user_level: z.string().max(100),
        user_permit: z.string(),
        user_active: z.string().max(1),
        user_display: z.string().max(200),
        user_avatar: z.string().max(200),
        utoken: z.string().max(200),
        create_by: z.string().max(30),
        create_date: z.date(),
        modify_by: z.string().max(30),
        modify_date: z.date(),
        language: z.string().max(15),
        trash: z.number().int()
    });
}
